services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python3', 'backend.py']
    environment:
      - BOT_TOKEN=1
    volumes:
      - ./shared:/shared
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - ./shared/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
