services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python3', 'backend.py']
    environment:
      - BOT_TOKEN=1
    depends_on:
      db:
        condition:
          service_healthy
    volumes:
      - ./shared:/shared

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=test
    volumes:
      - ./shared/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  shared:
